# -----------------------------------------------------------------------------
# Site Settings
# -----------------------------------------------------------------------------

name: Sanjana Mendu
email: sm7gc@virginia.edu
description: Personal website of Sanjana Mendu.
url: 

# -----------------------------------------------------------------------------
# Social Integration
# -----------------------------------------------------------------------------
github_username: sm7gc
# twitter_username: 
linkedin_username: sanjana-mendu
scholar_userid: fZh9riIAAAAJ
# facebook_username: 
# orcid_id: 0000-0002-0766-610X
# medium_username:
# quora_username:
# publons_id:
# research_gate_profile: Sanjana_Mendu
# blogger_url:

contact_note: >
  The best way to reach me is via email

google_analytics: UA-XXXXXXXXX

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: page
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/
  posts:
    output: true
    permalink: /posts/:path/

news_limit: 10

# -----------------------------------------------------------------------------
# Jekyll Settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
# highlighter: pygments

# Include/Exclude
include: ['_pages']
exclude: [node_modules]

# Plugins
plugins:
  - jekyll-paginate
  - jekyll/scholar
  - jemoji

# Jekyll-Scholar
scholar:
  last_name: Mendu
  style: apa
  locale: en
  sort_by: year
  order: descending
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: publication
  reference_tagname: div

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------

jquery_version: "1.12.4"
katex_version: "0.7.1"
anchorjs_version: "3.2.2"

# # -----------------------------------------------------------------------------
# # Blog
# # -----------------------------------------------------------------------------
# blog_name: blog
# blog_description: a simple platform for an ocassional brain dump

# # Pagination
# paginate: 4
# permalink: /blog/:year/:title/
# paginate_path: /blog/page:num/

# text:
#   pagination:
#     newer: 'Newer'
#     older: 'Older'